ShoalCave_LowTideEntranceRoom_Text_AreYouPlanningOnGoingInThere:
	.string "Are you planning on going deep\n"
	.string "in there?\p"
	.string "How about bringing me back some\n"
	.string "SHOAL SALT and SHOAL SHELLS?\p"
	.string "I can give you something good if\n"
	.string "you bring me the ingredients.$"

ShoalCave_LowTideEntranceRoom_Text_BringMe4ShoalSaltAndShells:
	.string "If you bring me either of the\n"
	.string "SHOAL SALT and SHOAL SHELLS,\l"
	.string "I will give you a HEART SCALE…\p"
	.string "You can get those ingredients\n"
	.string "every day.$"

ShoalCave_LowTideEntranceRoom_Text_WouldYouLikeShellBell:
	.string "Oh, hey! SHOAL SALT or SHOAL SHELLS!\n"
	.string "And enough of them, too!\p"
	.string "Would you like me to give you\n"
	.string "a HEART SCALE for them?$"

ShoalCave_LowTideEntranceRoom_Text_MakeShellBellRightAway:
	.string "All righty, then! I'll give you\n"
	.string "a HEART SCALE right away.\p"
	.string "… … … … … … … …\n"
	.string "… … … … … … … …\p"
	.string "There! Done!$"

ShoalCave_LowTideEntranceRoom_Text_ExplainShellBell:
	.string "Have a POKéMON hold on to that.\n"
	.string "It'll love it, that's for certain.\p"
	.string "Why, the SHELL BELL's chime…\n"
	.string "It's simply sublime!\p"
	.string "You can get its ingredients every day,\n"
	.string "I'll give a HEART SCALE right away.$"

ShoalCave_LowTideEntranceRoom_Text_WantedToMakeShellBell:
	.string "Oh… Is that so…\n"
	.string "I wanted to trade a HEART SCALE…$"

ShoalCave_LowTideEntranceRoom_Text_NoSpaceInYourBag:
	.string "You don't have space in your BAG\n"
	.string "if I were to make it for you.\p"
	.string "You should make room and come back\n"
	.string "for a HEART SCALE.$"

ShoalCave_Text_WasShoalSaltNowNothing:
	.string "There was some SHOAL SALT here.\n"
	.string "But, there's nothing here now.$"

ShoalCave_Text_WasShoallShellNowNothing:
	.string "There was a SHOAL SHELL here.\n"
	.string "But, there's nothing here now.$"
